#!/bin/bash

# filename : forprinter(base on interaction script).

# first of first,include abs root(directory) name.

# then start 'Quartet Limited'

# get some global variable -- "FUNCPATH" "ABSROOT" "include_all" "echotest" ..

project_dir=$( cd  $( dirname $0 ) &&  cd ../../ && pwd -P )
. $project_dir/conf/abs.conf
. $project_dir/conf/options.conf

. ${FUNCPATH}/base 2>/dev/null

# include ours
. fuchanpin/functions/base

# disable all development's debug info.
LEVEL=4 
if [ "$#" -ne 1 ];then
	echo Usage: $0 HOW_MANY_QUESTIONS
	exit 1
fi

if [ ! -f fuchanpin/sample_"$1".conf ];then
	echo No Found fuchanpin/sample_"$1".conf file
	exit 1
fi

# prepare level
# test python version(2.7 or 3.4? or 3.5?(2016-4 new)) 
#MINGW64_NT-10.0 DESKTOP-LGV520D 2.5.0(0.295/5/3) 2016-03-31 18:47 x86_64 Msys
if [[ `uname -a` == *MICROSO-UTR1LM8* ]];then
	eval "shufflenum=$( python fuchanpin/help34.py $1 )"
elif [[ `uname -a` == MINGW64_NT* ]];then
	eval "shufflenum=$( python fuchanpin/help35.py $1 )"
else
	eval "shufflenum=$( python fuchanpin/help27.py $1 )"
fi
	
#echo shufflenum array said total ${#shufflenum[@]} items\.
# prepare question(records)
# $1 is 'HOW_MANY_QUESTIONS'(num)
letfull fuchanpin/sample_"$1".conf


#echo "${records[@]}"
#echo records array said total ${#records[@]} items\.

# check if ${#records[@]} equal ${#shufflenum[@]}
if [ ${#records[@]} -eq 0 ];then
	echo there is a problem occurs::questions amount is 0\,repair it\.
	exit 1
elif [ ${#shufflenum[@]} -eq 0 ];then
	echo there is a problem occurs::order number is 0\,repair it\.
	exit 1
elif [ ${#records[@]} -ne ${#shufflenum[@]} ];then
	echo there is a problem occurs::order number amount NOT equal question amount\,repair it\.
	exit 1
fi

################# above all from 'interaction' script. ###################

for i in $(seq 0 $(( ${#records[@]} -1 )) )
do
# (for *unix )
#	forprinter[$i]="${records[$i]}""=\n\n"

# (for windows )
	forprinter[$i]="${records[$i]}""=\r\n"
done
fromdatesign=`date | tr -d '\ ' | tr  "[:]" "[\.]"`
echo -en "${forprinter[@]}"  > "${ABSROOT}""/fuchanpin/forprinter/printing""${fromdatesign}"".txt"

exit 0
