#!/bin/bash
# filename : interaction # be careful here,if name is '*.sh',will about no-end include

# first of first,include abs root(directory) name.
# then start 'Quartet Limited'
# get some global variable -- "FUNCPATH" "ABSROOT" "include_all" "echotest" ..
project_dir=$( cd  $( dirname $0 ) &&  cd ../../ && pwd -P )
. $project_dir/conf/abs.conf
. $project_dir/conf/options.conf

. ${FUNCPATH}/base 2>/dev/null

# include ours
. fuchanpin/functions/base

# disable all development's debug info.
LEVEL=4 
if [ "$#" -ne 1 ];then
	echo Usage: $0 HOW_MANY_QUESTIONS
	exit 1
fi

if [ ! -f fuchanpin/sample_"$1".conf ];then
	echo No Found fuchanpin/sample_"$1".conf file
	exit 1
fi


# prepare level
# test python version(2.7 or 3.4? or 3.5?(2016-4 new)) 
#MINGW64_NT-10.0 DESKTOP-LGV520D 2.5.0(0.295/5/3) 2016-03-31 18:47 x86_64 Msys
if [[ `uname -a` == *MICROSO-UTR1LM8* ]] || [[ `uname -a` == *ALANCOMPUTER* ]];then
	eval "shufflenum=$( python fuchanpin/help34.py $1 )"
elif [[ `uname -a` == MINGW64_NT* ]];then
	eval "shufflenum=$( python fuchanpin/help35.py $1 )"
else
	eval "shufflenum=$( python fuchanpin/help27.py $1 )"
fi
	
#echo shufflenum array said total ${#shufflenum[@]} items\.
# prepare question(records)
# $1 is 'HOW_MANY_QUESTIONS'(num)
letfull fuchanpin/sample_"$1".conf

#echo "${records[@]}"
#echo records array said total ${#records[@]} items\.

# check if ${#records[@]} equal ${#shufflenum[@]}
if [ ${#records[@]} -eq 0 ];then
	echo there is a problem occurs::questions amount is 0\,repair it\.
	exit 1
elif [ ${#shufflenum[@]} -eq 0 ];then
	echo there is a problem occurs::order number is 0\,repair it\.
	exit 1
elif [ ${#records[@]} -ne ${#shufflenum[@]} ];then
	echo there is a problem occurs::order number amount NOT equal question amount\,repair it\.
	exit 1
fi
############# output a text,manman need it this vacation. ###############

for i in $(seq 0 $(( ${#records[@]} -1 )) )
do
# (for *unix )
#	forprinter[$i]="${records[$i]}""=\n\n"

# (for windows )
	forprinter[$i]="${records[$i]}""=\r\n"
done
fromdatesign=`date | tr -d '\ ' | tr  "[:]" "[\.]"`
test -d "${ABSROOT}""/fuchanpin/forprinter/" || mkdir "${ABSROOT}""/fuchanpin/forprinter/" 
echo -en "${forprinter[@]}"  > "${ABSROOT}""/fuchanpin/forprinter/printing""${fromdatesign}"".txt"


# now start interaction.
echo
echo
echo '****************************************************************'
echo '****************************************************************'
echo '******  Welcome My Friend To A Interesting Calulator Game ******'
echo '****************************************************************'
echo '****************************************************************'
echo
echo
echo '----------------------------- use log ----------------------' >> fuchanpin/game.log
date >> fuchanpin/game.log

start_t=`date +%s`
for i in $(seq 0 $(( ${#shufflenum[@]} -1 )) )
do
	flushindex=${shufflenum[$i]}
	ask ${records[$flushindex]}
	if test $? -ne 0;then
		break		
	fi
done


# echo "till here,\$curnum==$curnum and \${#shufflenum[@]}==""${#shufflenum[@]}"
if [ $curnum -ne $(( 1 + ${#shufflenum[@]} )) ]
then
	#cat fuchanpin/sample_"$1".conf >> fuchanpin/game.log
	sed -e '/^\ *#/d' -e '/^$/d' fuchanpin/sample_"$1".conf >> fuchanpin/game.log
	echo -en '\t\t***** non-finish *****\n' >> fuchanpin/game.log 
	echo '(end) ----------------------  use log ----------------------' >> fuchanpin/game.log
	echo 'non-finish'  
	exit 1
fi

end_t=`date +%s`
echo 'total '"${#shufflenum[@]}"' questions.'
echo 'time = '"$(( end_t - start_t ))"' seconds.'
# write to game log.
echo 'total '"${#shufflenum[@]}"' questions.' >> fuchanpin/game.log

#cat fuchanpin/sample_"$1".conf >> fuchanpin/game.log
sed -e '/^\ *#/d' -e '/^$/d' fuchanpin/sample_"$1".conf >> fuchanpin/game.log
echo 'time = '"$(( end_t - start_t ))"' seconds.' >> fuchanpin/game.log
echo '(end) ----------------------  use log ----------------------' >> fuchanpin/game.log
echo >> fuchanpin/game.log
