#!/bin/bash

# the base of all test-function.
# can override below 2 vars till meet your needs.
# DEBUG level 0 -- No debug 
# DEBUG level 1 -- simple debug info
# DEBUG level 2 -- more detail about debug info
# if fall into product-time,comment above and uncomment below line:
# declare -i DEBUG=0

declare -i DEBUG=2

FILENAME=$( basename $0 2>/dev/null )
declare DEBUGTITLE="[${FILENAME}  +]"

# all of simple password
declare SIMPLE_PASSWORD="0 00 01 02 03 10 11 12 13 20 21 22 23 30 31 32 33"

# share dir
declare SHARE_D="${ABSROOT}/share"

# declare a directory for uploading
declare UPLOADS="${ABSROOT}/uploads"

function include_all(){
	for file in ${FUNCPATH}/*.sh
	do
		. $file
	done
}
function huali(){
	echo '   -------------------------------------------------------'
	echo '   ----------------- HUA LI SEPARATOR LINE  --------------'
	echo '   -------------------------------------------------------'
}
function echotest(){
	echo $DEBUGTITLE "$1" #it is import to let all echo msg in a double quote!
}

# iisr=if i say right
function iisr(){
	#"$1" is a expression ,value is boolean '1' or '0'
	if test $1;then
		echo "::TRUE:: ""$1" 
	else
		echo "::ERROR:: ""$1" 
	fi
}
#invoke include method now.
include_all
